### ISSUE TITLE
scdrs perform-downstream: fail to load scDRS full score gz file

### ISSUE THREAD

**Issue by hopehan12** [martinjzhang/scDRS#101]
Hi, 

I am trying to run scdrs perform-downstream, but it keeps showing the error that cannot find the full score directory. Could you help me with this?

![image](https://github.com/user-attachments/assets/15cc64b4-7b3c-46fa-9ed9-73fefcf3e736)
![image](https://github.com/user-attachments/assets/8f140f70-2336-4b29-a0fe-d26d2e1ef07c)

scdrs perform-downstream --h5ad-file seurat3.h5ad --score-file outfolder23Aug/HTN.full_score.gz --out-folder outfolder26Aug --group-analysis Celltype

NotADirectoryError: [WinError 267] The directory name is invalid: 'outfolder23Aug/HTN.full_score.gz'

Many thanks!

**Comment by martinjzhang** [comment]
Have you tried using the absolute path? Also, consider running scDRS in a Unix system. I think there may be some compatibility issue with the Windows system.

**Comment by hopehan12** [comment]
Hi Martin,

Yes, I tried using the absolute path but it didn't work. But it works perfectly fine in a Unix system! Thank you very much!
