### ISSUE TITLE
Why are some of the CORR columns in the <trait>.scdrs_gene file negative, and the largest RANK level is the smallest negative number, can this represent the gene most associated with disease and cell type?

### ISSUE THREAD

**Issue by MoWeiLanChen** [martinjzhang/scDRS#102]
Why are some of the CORR columns in the <trait>.scdrs_gene file negative, and the largest RANK level is the smallest negative number, can this represent the gene most associated with disease and cell type?
I checked your code and found that this value comes from the norm_score column in the <trait>.full_score.gz file calculated in the first step. This column value also has negative numbers. But I don't understand the detailed calculation process. Look forward to hearing from you.

**Comment by martinjzhang** [comment]
Smallest RANK (order) should be the gene that's most associated (usually with a positive correlation).
