### ISSUE TITLE
About the H5AD input - raw counts or normalized+transformed?

### ISSUE THREAD

**Issue by hopehan12** [martinjzhang/scDRS#103]
Hi,

Thanks for the great work!
I have a question about the H5AD file for scDRS. I already processed my single-cell data in Seurat so I extracted RNA assay counts to h5ad file (raw counts). But I read the paper found out it needs to be normalized and transformed. Now I am trying to run with normalized and transformed h5ad but it gives me warning when I am running the compute-score function
'Loading data:
WARNING: adata.X seems to be already log-transformed.'

I am just wondering which types of H5AD file should I provide as input? Raw counts or normalized+transformed?
Please just let me know! Many thanks.

**Comment by martinjzhang** [comment]
You can just supply the raw count data and specify the flag `--flag-raw-count True`

**Comment by hopehan12** [comment]
Thank you Martin! Really helpful :)
