### ISSUE TITLE
Sig. cell type-disease associations and Sig. individual cells

### ISSUE THREAD

**Issue by hopehan12** [martinjzhang/scDRS#104]
Hi Martin,

Thanks for the great work! 
I finished the analysis and I am kinda stuck with interpreting the results.
I have 0 significant individual cells (0 out of 252452 cells) but significant cell type-disease associations in some cell types (2 out of 12 cell types). I am wondering if this is because of generally higher disease scores across cells within that cell type?

Please just let me know, many thanks!

**Comment by martinjzhang** [comment]
You are correct. Cell type-level analysis can be more powerful if cells within a cell type have consistently higher disease scores (which may not be significant for individual disease cells).

**Comment by martinjzhang** [comment]
We plan to release a significantly more powerful version in a few months. Stay tuned.

**Comment by hopehan12** [comment]
Hi Martin,
Thank you! Super helpful. I will keep an eye out for it!
