### ISSUE TITLE
Problem with applying gene-disease association from TWAS result

### ISSUE THREAD

**Issue by Stray357** [martinjzhang/scDRS#105]
Hi, 
Thank you for providing such an instresting tool.
I was trying to use custom gene set from TWAS result instead of GWAS result outputted from MAGMA. The code I use to generate .gs file is this:
`scdrs munge-gs \
    --out-file "<output_dir>/result.gs" \
    --zscore-file "<gene_list_dir>/gene_list.tsv" \
    --weight zscore \
    --n-max 1000`   

My gene_list.tsv file looks like this, with 515 genes in total :
![image](https://github.com/user-attachments/assets/1d642367-043c-4ebc-bd39-f564b4adb1fe)

I ran the "scdrs compute-score" as CLI , and got score file with all 0 and NA items in the "raw_score" column, and all NA in the "norm_score" column

I have tested the environment and my h5ad file with the reference .gs file as provided on https://figshare.com/articles/dataset/scDRS_data_release_030122/19312583?file=34300898
The score file is normal and the program works perfectly fine, so it should be the problem with my gs file.

I checked the reference .gs file carefully and found that all the weight in the .gs file is non-negative, while in my .gs file, there are negative weights and for some gene with z score below -9, the weight shows "-inf" .

I assume that MAGMA do not output negative z score since the gene-disease association from GWAS alone do not really have a direction. However, in TWAS, the negative z score outputted by standard pipeline like PrediXcan does mean a negative association between the gene expression level and disease risk.

So, my question is, how can I apply the  TWAS result in scDRS ? Should I just filter and retain the positively associated gene from TWAS while discard the negatively associated gene ? Is there any possible ways I can keep the information provided by the negatively associated genes ?

Thanks a lot!

**Comment by martinjzhang** [comment]
Hi, 

Maybe you can convert the z-scores to p-values? scDRS doesn't use the sign of the genes.

**Comment by Stray357** [comment]
Hi, 
Thanks for the timely response. I have tested the p-value approach, and it worked out perfectly.
