### ISSUE TITLE
Downstream Analysis - invalid value encountered in scalar divide

### ISSUE THREAD

**Issue by NaomiHuntley** [martinjzhang/scDRS#110]
Hello, 

I am looking for some guidance on this output I got when I ran the perform-downstream function. My output log shows that the group-analysis and gene-analysis finished, and then below the error below. I just want to confirm that this is not due to some preprocessing that I should do with my single cell dataset and that it will not negatively impact the results I got during this step. 

Thank you in advance for the support with using this method! 
~Naomi 

### **Here is the output in question:** 
/storage/home/neh5207/.conda/envs/UMAP/lib/python3.12/site-packages/scdrs/method.py:957: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for group, df_group in df_meta.groupby(groupby):
/storage/home/neh5207/.conda/envs/UMAP/lib/python3.12/site-packages/scdrs/method.py:1076: RuntimeWarning: invalid value encountered in scalar divide
  C = numer / denom

### **Here is the full output:** 
Performing scDRS group-analysis
`connectivities` not found in `adata.obsp`; run `sc.pp.neighbors` first
Finish group-analysis for genus..Eubacteriumbrachygroup.id.11296.out.tsv.gs (sys_time=9176.8s)

Performing scDRS gene-analysis
Finish gene-analysis for genus..Eubacteriumbrachygroup.id.11296.out.tsv.gs (sys_time=9262.4s)

/storage/home/neh5207/.conda/envs/UMAP/lib/python3.12/site-packages/scdrs/method.py:957: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for group, df_group in df_meta.groupby(groupby):
/storage/home/neh5207/.conda/envs/UMAP/lib/python3.12/site-packages/scdrs/method.py:1076: RuntimeWarning: invalid value encountered in scalar divide
  C = numer / denom

**Comment by martinjzhang** [comment]
It seems to be a corner case when some groups have very few cells. Maybe try to remove cell groups with very few cells (e.g., requiring n_cell>25 for all groups)?

**Comment by NaomiHuntley** [comment]
That worked! Thank you!
