### ISSUE TITLE
MC-z and MC-z-based p-value

### ISSUE THREAD

**Issue by martinjzhang** [martinjzhang/scDRS#17]
1. Change the column name of "zscore" to "mc_zscore", to be consistent with "mc_pval" 
2. Additionally output one-sided p-values based on the normal distribution and `mc_zscore` ("MC-z"), maybe with column name of "mcz_pval".

**Comment by KangchengHou** [comment]
perhaps we should have 2 columns 'pval' and 'zscore' where we place the recommended statistics to default usage so user don't have to think much on choosing among columns (for sure we put other numbers for completeness)

for group-level stats, pval would be mc-pvalue, and z-score would be zscore based on normal distribution?

**Comment by martinjzhang** [comment]
Good idea to have pval and zscore as the recommended stats and append others at the end. I will update it in v1.0.2 and also make sure it is backward compatible.
