### ISSUE TITLE
Cleaning/prepping GWAS statistics

### ISSUE THREAD

**Issue by rbutleriii** [martinjzhang/scDRS#19]
Hello, I couldn't find it in the paper. For these GWAS traits, do you do any pruning prior to magma? (i.e. exclude HLA region, limit to Hapmap3 SNPs)

Thanks

**Comment by martinjzhang** [comment]
Hi, 

Sorry for the confusion! We have removed the MHC region (CHR6 25-34MB) and restricted the summary statistics to the HAPMAP3 SNPs. 

Best,
Martin

**Comment by rbutleriii** [comment]
Thanks!
