### ISSUE TITLE
Problem with munging

### ISSUE THREAD

**Issue by HJ234** [martinjzhang/scDRS#37]
Hi, Thank you for the great program. 
I'm trying to run scDRS on one trait, but I seem to get no gene sets after munging with scdrs munge-gs

```
Call: scdrs munge-gs \
--zscore-file SLE.genes.out.zstat.tsv \
--weight zscore \
--n-min 10 \
--n-max 1000 \
--out-file munge_top1000Z.gs

--zscore-file loaded: n_gene=19025, n_trait=1 (sys_time=0.0s)
Print info for the first 3 traits and first 10 genes
Traits               ['SLE']
SAMD11               [1.037]
NOC2L                [1.1508]
KLHL17               [1.5457]
PLEKHN1              [2.8403]
PERM1                [3.0402]
HES4                 [2.3732]
ISG15                [2.2022]
AGRN                 [2.7473]
RNF223               [2.6844]
C1orf159             [3.9652]
--zscore-file have values above 1 or below 0. Seems fine.

Finish munging 1 gene sets (sys_time=0.0s)
```
The resulting file looks like the following

<img width="331" alt="Screenshot 2022-10-03 at 19 52 16" src="https://user-images.githubusercontent.com/109527205/193655900-3d12addd-6ba5-4862-b874-732ad1b15886.png">

Would you know what the problem is? Thanks

**Comment by martinjzhang** [comment]
Hi, 

Thank you for reporting this issue. I couldn't identify the cause based on just the .log file. Could you send us a minimal reproducible example (e.g., your zscore file)?

**Comment by HJ234** [comment]
Hi, thanks for the quick reply. I've sent the zstat file I've been using to "jinyezhang@hsph.harvard.edu" and I'm using scDRS 1.0.2.

**Comment by martinjzhang** [comment]
Hi @HJ234 

Thank you for sharing the .zscore file. I ran `scdrs munge-gs` on your `.zscore` file but couldn't reproduce the issue. I sent you the code and the generated `.gs` file via email.  

As a result, I am afraid I still couldn't identify the cause of the issue. Are you using Linux? Could you try to reinstall scDRS using `virtualenv` (e.g., https://harvardmed.atlassian.net/wiki/spaces/O2/pages/1588662166 for a tutorial)? If the issue persists, I can push a version of scDRS with more diagnostic information and ask you to run the new version on your data to hopefully identify the issue.

**Comment by HJ234** [comment]
Hi Martin,

Thank you for sending me over the .gs file. I've fixed the issue now. but still don't know what the problem was. I haven't changed anything since last time but it seems to work now. Sorry I can't provide you with analytics and suggest any causes at the moment.

**Comment by martinjzhang** [comment]
Thank you @HJ234 and good to hear that you are getting interesting results. We are actively developing the packages. I hope we can release some cool features real soon!

**Comment by DonaldSandoz2000** [comment]
> Hi, Thank you for the great program. I'm trying to run scDRS on one trait, but I seem to get no gene sets after munging with scdrs munge-gs
> 
> ```
> Call: scdrs munge-gs \
> --zscore-file SLE.genes.out.zstat.tsv \
> --weight zscore \
> --n-min 10 \
> --n-max 1000 \
> --out-file munge_top1000Z.gs
> 
> --zscore-file loaded: n_gene=19025, n_trait=1 (sys_time=0.0s)
> Print info for the first 3 traits and first 10 genes
> Traits               ['SLE']
> SAMD11               [1.037]
> NOC2L                [1.1508]
> KLHL17               [1.5457]
> PLEKHN1              [2.8403]
> PERM1                [3.0402]
> HES4                 [2.3732]
> ISG15                [2.2022]
> AGRN                 [2.7473]
> RNF223               [2.6844]
> C1orf159             [3.9652]
> --zscore-file have values above 1 or below 0. Seems fine.
> 
> Finish munging 1 gene sets (sys_time=0.0s)
> ```
> 
> The resulting file looks like the following
> 
> <img alt="Screenshot 2022-10-03 at 19 52 16" width="331" src="https://user-images.githubusercontent.com/109527205/193655900-3d12addd-6ba5-4862-b874-732ad1b15886.png">
> 
> Would you know what the problem is? Thanks

--zscore-file loaded: n_gene=62787, n_trait=0 (sys_time=0.0s)
Print info for the first 3 traits and first 10 genes
Traits               []
PSRC1,-9.289225811   []
AL592148.3,-7.992844093 []
MIA3,-7.120338886    []
TCF21,-6.520148163   []
SLC22A1,-6.220870419 []
NOS3,-6.197266755    []
NBEAL1,-6.112940111  []
ICA1L,6.017449523    []
LIPA,5.811769649     []
AL359922.2,5.799499614 []
Warning: zscore-file values are all between 0 and 1.
Do you know what causes this?
