### ISSUE TITLE
Issues with generating gs files

### ISSUE THREAD

**Issue by Li-mengjie** [martinjzhang/scDRS#38]
Hello, when I used this software to generate xx.gs files with weights, I found that the xx.gs file contained many negative values. Is this normal ?Such as: ZSCAN31:-0.16077,CMC2:-0.17637,PRH1:-0.17909,FDXR:-0.18069,PROM2:-0.18672,IFI35:-0.19512,AP001029.1:-0.19552,AC087500.2:-0.19587,LINC00642:-0.20189,TLCD3A:-0.20189,AC011468.5:-0.21043. 
![image](https://user-images.githubusercontent.com/99384654/193809463-e8ce169c-2eb5-4ff0-a50a-eaafbcd56284.png)

**Comment by martinjzhang** [comment]
Hi, 

This is not normal. scDRS uses one-sided z-scores where negative values correspond to non-significant p-values (>0.5). The negative weights shouldn't appear unless you have fewer than 1000 genes with `P<0.5` (if you use p-value file) or `Z>0` (if you use z-score file). If your z-scores are two-sided, you can either convert them to p-values or take the absolute value of the z-scores.
