### ISSUE TITLE
scdrs CLI not working?

### ISSUE THREAD

**Issue by Dzhan4** [martinjzhang/scDRS#45]
Sorry if this is a silly question. I followed the instructions and installed scdrs v1.0.2:

```
git clone https://github.com/martinjzhang/scDRS.git
cd scDRS
git checkout -b v102 v1.0.2
pip install -e .
```

But when I go to the folder with the binary executable and type `./scdrs`, it gives me this error:

```
  File "./scdrs", line 26
    h5ad_file: str,
             ^
SyntaxError: invalid syntax
```

I feel like I'm missing something obvious here, but I can't figure out what.

**Comment by KangchengHou** [comment]
Thanks for the question. python version seems to be the issue here. What python version are you using? We recommend using >=3.7

**Comment by Dzhan4** [comment]
Thanks for the reply. I'm using python 3.9.6

```
ml

Currently Loaded Modules:
  1) git/2.24.1   2) autotools/1.1   3) cmake/3.20.2   4) xalt/2.10.37   5) TACC   6) libfabric/1.7.0   7) intel/19.1.1   8) impi/19.0.9   9) python3/3.9.6
```

**Comment by KangchengHou** [comment]
That's great and we will add a note in the installation page.
