### ISSUE TITLE
Adjusting for donor effects

### ISSUE THREAD

**Issue by Ararder** [martinjzhang/scDRS#48]
Hi! Thanks very much for the great work behind scDRS. It's great to use.

I was wondering if you have thoughts on how to adjust for potential donor effects?
Is it best to add one-hot encodings for each donor, or provide one column with a different value for each donor?.

**Comment by martinjzhang** [comment]
Hi @Ararder 

Thank you for the question. You can use the `scdrs compute-score --cov-file` function to adjust for donor effects. To do so, you can add one-hot encoding of each donor (all but one) to the `.cov` file. For example, if there are 3 donors, the `.cov` file should contain 3 binary variables: `const` (all 1), `donor1`, and `donor2`.
