### ISSUE TITLE
GWAS traits and a control traits

### ISSUE THREAD

**Issue by Li-mengjie** [martinjzhang/scDRS#49]
Hello! I have a problem and I hope to get your help. I was going to incorporate multiple GWAS traits and a control (height) for the study but couldn't figure out how to produce a gs-file. One trait and height are listed in the tutorial. If you add traits, do you need to list multiple traits and height at the same time, and take the intersection genes as the column? However, there is a problem with this. As the number of included traits increases, the number of shared genes decreases, which is not even enough to meet the analysis requirements. I wonder if there is any mistake in my understanding. I hope to get your reply.

**Comment by martinjzhang** [comment]
Hi @Li-mengjie , thank you for the question. 

There is no need to take the intersection. scDRS processes each trait (one row in the .gs file) separately. In other words, putting all traits in the same file or having a different file for a trait gives the same results. So you can either put all traits in the same .gs file (one row per trait) or process the traits separately using different .gs files.

**Comment by Li-mengjie** [comment]
Thanks for your reply. I will have a try.

**Comment by Li-mengjie** [comment]
Thank you for your reply. I understand what you mean. But there's still some doubt about my question. I would like to know if I need to take the gene intersection of multiple study and control traits before producing the gs- file when working with them. If not, what should be done with the corresponding missing values?

**Comment by Li-mengjie** [comment]
For example, what should I do with this missing value

![屏幕截图 2022-12-05 121853](https://user-images.githubusercontent.com/99384654/205548725-f888585e-5aab-4d10-b6b3-858993e0df99.png)

**Comment by Li-mengjie** [comment]
Thanks for your reply. I will have a try.

**Comment by Li-mengjie** [comment]
Hello! Thank you for your patient answer. I found a problem with the next step. 
![微信图片_20221205175721](https://user-images.githubusercontent.com/99384654/205608311-611b5c8e-93e6-4096-b5f4-175ea41fb936.jpg)

In the next step, I used adata,obs: 133186x14151, but it did not run successfully and no errors were reported.
![微信图片_20221205175734](https://user-images.githubusercontent.com/99384654/205608684-f28ee643-6c11-4b5e-b623-2fa7ce3840f4.jpg)

 Then I use the same data, but not pre-processed, obs: 133186x50939; Again, it didn't run successfully, and no errors were reported. 
![微信图片_20221205175743](https://user-images.githubusercontent.com/99384654/205609565-417008b9-47e3-441b-9731-2b7f70799d2d.jpg)

Then I switched to the processed adata.obs41435x26675 and it ran successfully. What requirements should adata fulfill?
![微信图片_20221205175729](https://user-images.githubusercontent.com/99384654/205609524-7eee5050-4422-448d-b092-53bfd020b0ed.jpg)

**Comment by martinjzhang** [comment]
Hi @Li-mengjie , thank you for reporting the issue. Could you provide more details on "didn't run successfully"? Did the software just hang there? Were there any outputs in the .log file? 

I am unsure about the cause. There might be a memory issue. Have you allocated enough computing resources? For a data set with 133186x50939, I think scDRS needs around 32-48GB of RAMs. Filtering out low-quality genes and cells will substantially (and linearly) reduce the computational requirement. 

I suggest using the raw count data for scDRS, but removing low-quality genes and cells.

**Comment by Li-mengjie** [comment]
There was enough memory, and normally this step would have taken a long time, but in my case it ended in less than 2 minutes, with no report or error.
![微信图片_20221205182917](https://user-images.githubusercontent.com/99384654/205615068-684008b6-d458-44df-b112-120dccc3405f.jpg)

**Comment by martinjzhang** [comment]
Hi @Li-mengjie , the data needs to be in .h5ad format whose adata.X entry stores the raw count matrix. The file is parsed by the `anndata read_h5ad` function in scDRS. I notice that your input file is in `.h5` format instead of `.h5ad` format. Maybe that caused the issue?

**Comment by Li-mengjie** [comment]
Hello! Sorry for the error, I corrected the error later but still did not get the result, and the situation is the same as above. Later I observed that in the tutorial adata.X was unscaled, whereas in my data adata.X was already scaled. I don't know if that's the problem, but I'm trying.I hope you can get your advice. The following two graphs are tutorial data and my data respectively.
![微信图片_20221205205700](https://user-images.githubusercontent.com/99384654/205643029-9e89e3a1-99d2-46ec-a9cf-07daa63aef27.png)
![微信图片_20221205205705](https://user-images.githubusercontent.com/99384654/205643055-74a02208-a9d1-4919-a43e-f66986dee1fd.jpg)
