### ISSUE TITLE
tutorial-Quick start ——full_score.gz

### ISSUE THREAD

**Issue by zhouxilala** [martinjzhang/scDRS#50]
Hello! I have a problem and I hope to get your help. I was going to follow this tutorial-Quick start (https://martinjzhang.github.io/scDRS/notebooks/quickstart.html), but I am can't find the f"data/{trait}.full_score.gz" file successfully and I Unzip the file and find that it does not exist. I wonder if there is any mistake in my understanding. I hope to get your reply.

![331670508753_ pic](https://user-images.githubusercontent.com/115094181/206473534-7526129f-a7fa-4288-b307-a79da3e8d749.jpg)

![431670509566_ pic](https://user-images.githubusercontent.com/115094181/206473471-a56cd563-11e9-494d-9cf4-e710856296be.jpg)
![321670508719_ pic](https://user-images.githubusercontent.com/115094181/206473506-0be452ba-b4fe-4195-b21c-832d04c2266d.jpg)

**Comment by KangchengHou** [comment]
Hello and thanks for the question. These scores are computed at the previous cell of the notebook, please see attached

<img width="863" alt="image" src="https://user-images.githubusercontent.com/17946812/206545416-75b99973-aa71-45cd-bf60-600e71e988af.png">
