### ISSUE TITLE
scdrs compute-score output

### ISSUE THREAD

**Issue by NaomiHuntley** [martinjzhang/scDRS#57]
Hello and thank you for this great tool. I am running in to an issue at the scdrs compute-score step. 

Each of my traits are a separate .gs file at this point. Here is an example of the first few lines of one of the trait files: 
<img width="774" alt="Screenshot 2023-04-06 at 10 18 06 AM" src="https://user-images.githubusercontent.com/54378109/230405364-0cc1fff7-ebd9-4c7e-bc29-8ffff7dc5854.png">

Here is the code I am running: 
![image](https://user-images.githubusercontent.com/54378109/230405763-bb289f83-8361-467e-839d-90ca290d2f73.png)

But my output files are both not as expected: 
<img width="839" alt="Screenshot 2023-04-06 at 10 20 41 AM" src="https://user-images.githubusercontent.com/54378109/230405999-edd51108-68a7-4e5e-8c1c-5d135bf3a4ad.png">

I would really appreciate any insight that you have on this issue! 

Thank you!

**Comment by martinjzhang** [comment]
Hi @NaomiHuntley , 

`.gz` file is a compressed file, so `head` will not work. You can use `zcat` to read the compressed binary file and then use `head` to print out the first few lines. Can you try `zcat [file_name] | head` instead?

**Comment by martinjzhang** [comment]
Hi @NaomiHuntley ,

I think you named all your traits `ZSTAT` in the `.gs` file. Since `scdrs` specifies output file names using the trait name (which is `ZSTATS` for all your traits), all your traits may have the same output file names. So I think the new output results overwrote the old ones.

**Comment by NaomiHuntley** [comment]
That was the issue! Thank you
