### ISSUE TITLE
munge-gs input format

### ISSUE THREAD

**Issue by DonaldSandoz2000** [martinjzhang/scDRS#61]
--zscore-file loaded: n_gene=62787, n_trait=0 (sys_time=0.0s)
Print info for the first 3 traits and first 10 genes
Traits               []
PSRC1,-9.289225811   []
AL592148.3,-7.992844093 []
MIA3,-7.120338886    []
TCF21,-6.520148163   []
SLC22A1,-6.220870419 []
NOS3,-6.197266755    []
NBEAL1,-6.112940111  []
ICA1L,6.017449523    []
LIPA,5.811769649     []
AL359922.2,5.799499614 []
Warning: zscore-file values are all between 0 and 1.

Hi, when I'm using munge-gs to process a gene set csv file for a trait, it only reads all the rows, but it doesn't seem to be able to distinguish the two columns well, is there a mistake in the formatting of my csv file somewhere?

**Comment by martinjzhang** [comment]
Hi @DonaldSandoz2000 , 

scDRS uses `.tsv` files instead of `.csv` files https://martinjzhang.github.io/scDRS/file_format.html

Martin

**Comment by DonaldSandoz2000** [comment]
Oh, I made a stupid mistake. My previous tsv export in R didn't have tabs to separate the two columns.
Now I've corrected it and I've got the result I wanted! Thank you so much for your answer.
