### ISSUE TITLE
perform-downstream outputs zero significant cells

### ISSUE THREAD

**Issue by gwentea** [martinjzhang/scDRS#64]
Dear Author,

Thank you for such an informative tool.
When running scDRS compute-score, the command output and results seemed normal (see umaps below)
![image](https://github.com/martinjzhang/scDRS/assets/113828395/a4a28000-4ac9-4cd6-9a1d-96e753c6f0a9)
![image](https://github.com/martinjzhang/scDRS/assets/113828395/4e286d17-27fd-4398-8f36-08c669083a9f)

However, when running perform-downsteam, the number of significant cells is basically 0, resulting in all blank cells on the heat map (see below).
![image](https://github.com/martinjzhang/scDRS/assets/113828395/8f27fb7f-220f-41eb-957a-3367631111e1)
![image](https://github.com/martinjzhang/scDRS/assets/113828395/0a82aa2f-05db-4308-9deb-8dd94dd2c61c)

We are trying to locate the possible causes and what can be done to improve the results. It would be great if you could please provide any suggestions!
Thanks in advance!

**Comment by martinjzhang** [comment]
Hi, 

Thank you for sharing the results. The results look normal to me. scDRS may not have sufficient power in some cases, such as https://github.com/martinjzhang/scDRS/issues/3 or https://github.com/martinjzhang/scDRS/issues/30

Imputing the scRNA-seq data may help increase the power, such as https://github.com/martinjzhang/scDRS/issues/32 

Best,
Martin
