### ISSUE TITLE
plot_group_stats() got an unexpected keyword argument 'plot_kws'

### ISSUE THREAD

**Issue by milospjanic** [martinjzhang/scDRS#65]
Hi,

I am getting this error when trying to plot. Using both scdrs 1.0.1 and 1.0.2

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [23], in <cell line: 23>()

---> 23 fig, ax = scdrs.util.plot_group_stats(
     24     dict_df_stats={
     25         trait: df_stats.rename(index=dict_celltype_display_name)
     26         for trait, df_stats in dict_df_stats.items()
     27     },
     28     plot_kws={
     29         "vmax": 0.2,
     30         "cb_fraction":0.12
     31     }
     32 )

TypeError: plot_group_stats() got an unexpected keyword argument 'plot_kws'

**Comment by martinjzhang** [comment]
@KangchengHou could you help? Thanks!

**Comment by KangchengHou** [comment]
@milospjanic looks like it is a version mismatch issue.

Can you type
```python
scdrs.__version__
??scdrs.util.plot_group_stats
```
to provide us some information on the scdrs version you are using?

To have a quick fix, I suggest installing scdrs=1.0.3 or remove plot_kws when calling plot_group_stats

**Comment by milospjanic** [comment]
scdrs.__version__
'1.0.2'

**Comment by milospjanic** [comment]
Removing plot_kws works but then i cant adjust vmax for the coloring, and the graph ends up with no color (as the FDR proportions are lower)

**Comment by KangchengHou** [comment]
can you try reinstalling scdrs=1.0.3 so you can have more control on the figure aesthetics via plot_kws

**Comment by milospjanic** [comment]
How do i get 1.0.3, pip install scdrs==1.0.3 doesnt work

**Comment by KangchengHou** [comment]
```
pip install git+https://github.com/martinjzhang/scDRS.git
```

**Comment by KangchengHou** [comment]
can you try setting `cb_vmax`? the full option is available at 
https://github.com/martinjzhang/scDRS/blob/6ee2161820fc9141eb1f85512659eef1c05d0d66/scdrs/util.py#L492

**Comment by milospjanic** [comment]
works now, thanks!
![image](https://github.com/martinjzhang/scDRS/assets/12768624/7a881069-269c-40d7-a553-4930e51ffe82)

**Comment by wy-cmd** [comment]
Hello everyone, I would like to ask how to view the complete heatmap results. When I use the code below to create a heatmap, no matter how I set the canvas size for saving, I can't see the entire image. Could you please give me some advice? Thank you very much. Just to let you know, I am using the latest version, v1.03. 

` fig, ax = scdrs.util.plot_group_stats(
    dict_df_stats={
        trait: df_stats.rename(index=dict_celltype_display_name)
        for trait, df_stats in dict_df_stats.items()
    },

    plot_kws={
        "cb_vmax": 0.2,
        "cb_fraction":0.1,
    }
)

fig.set_size_inches(8, 10)
plt.savefig("Figure2.png")
plt.close(fig) `

When I do not set the image size, the result is as shown in Figure 1. However, when I set the image size, the result is as shown in Figure 2.
![Figure1](https://github.com/martinjzhang/scDRS/assets/76642080/15de9aa6-6772-4730-9bf1-e999d512a1a8)
![Figure2](https://github.com/martinjzhang/scDRS/assets/76642080/0c089072-1bbd-4c46-97cc-29962ebdaf40)

**Comment by KangchengHou** [comment]
Could you try `plt.savefig("Figure2.png", bbox_inches='tight')

**Comment by wy-cmd** [comment]
> Could you try `plt.savefig("Figure2.png", bbox_inches='tight')`

Thanks a lot! The image turned out great, nothing got cut off.
![Figure2](https://github.com/martinjzhang/scDRS/assets/76642080/b3a4a64e-1dde-4536-813d-17f0c011379c)
