### ISSUE TITLE
turning off fdr correction

### ISSUE THREAD

**Issue by milospjanic** [martinjzhang/scDRS#66]
Hi, is there any option to turn off fdr correction while plotting scdrs.util.plot_group_stats. I would like to plot on the graph the same pvalues i get with scdrs.method.downstream_group_analysis. Right now i see they are different, way less significant pvals on the plot than in df:stats, i guess probably due to fdr correction. Thanks

**Comment by KangchengHou** [comment]
Hi you can provide `df_fdr_prop`, `df_assoc_fdr`, and `df_hetero_fdr` to `plot_group_stats`. All these are #traits x #celltypes matrices. You can look up https://github.com/martinjzhang/scDRS/blob/6ee2161820fc9141eb1f85512659eef1c05d0d66/scdrs/util.py#L469
to converting the dict_df_stats to these matrices.

Let me know if you have success on this.
