### ISSUE TITLE
Gene weights or without gene weights

### ISSUE THREAD

**Issue by QianChwnLyn** [martinjzhang/scDRS#71]
Hi, I would like to ask what the impact is on the results of whether the gene set **gs file** contains the weight value. I discovered while watching magma tutorials that I did not understand how to calculate. By extracting the p-value of the SNPs for each gene set in the gwas results? Or what impact will it have on my results if I don't calculate the weight value?

**Comment by martinjzhang** [comment]
Hi @QianChwnLyn 

You can use the z scores that the MAGMA software generates. 

If you go without the gene weights, the method will lose some power (e.g., 10-30% depending on the dataset).

**Comment by schnappi-wkl** [comment]
Hi martin，
i also encountered the similar issue, i have some genesets associated with milk producting trait of buffalo  without corresponding the GWAS database unfortunately. i want to associate these traits with tissue or celltype,  could you give me some advices? 
thanks Schnappi

**Comment by martinjzhang** [comment]
Hi @schnappi-wkl 

It's fine to go without the gene weights. The method will lose some power (e.g., 10-30% depending on the dataset). But the results should be well-calibrated.
