### ISSUE TITLE
custom gene set ?

### ISSUE THREAD

**Issue by zhangpicb** [martinjzhang/scDRS#73]
Dear @KangchengHou ,

Thanks for your great tool!

I have a question about make custom gene set. I read the [custom gene set](https://github.com/martinjzhang/scDRS/issues/2).

Step2 --snp-loc ${magma_dir}/g1000_eur.bim ,1kg SNPs are used.

But before I read the issue,I use the SNPs in the GWAS summary data to annotate gene,and then using the output file to Step3.

I follow (https://github.com/martinjzhang/scDRS/issues/2) to get gene set. And I find the these 2 output gene.out files are different.
Maybe Step2 --snp-loc should use SNPs in GWAS summary?

Thanks in advanced!

```bash


# Step 2: make gene annotation file for MAGMA using the following command, this only needs to be done
# once for different GWAS summary statistics, and the file will be saved to out/step1.genes.annot
mkdir -p out/step1
${magma_dir}/magma \
    --annotate window=10,10 \
    --snp-loc ${magma_dir}/g1000_eur.bim \
    --gene-loc ${magma_dir}/NCBI37.3.gene.loc \
    --out out/step1

```

**Comment by KangchengHou** [comment]
Yes you can use your `.bim` file. Just create `.bim` file that match with your GWAS summary.

**Comment by zhangpicb** [comment]
Thanks for your quick reply!
