### ISSUE TITLE
Subsetting cells for downstream analysis.

### ISSUE THREAD

**Issue by jeji0209** [martinjzhang/scDRS#77]
Hello. Thank you for the development of this amazing tool.
I have one question about conducting the downstream analysis.

Is it statistically acceptable to subset my anndata and `full_score.gz` file when conducting downstream analysis?
The flow I am thinking is:

1. Run `compute-score` on my entire dataset to find cell types (e.g. cell type A) that are highly associated with a given trait.
2. Subset only cell type A cells, and the `full_score.gz` file of the cells and run `perform-downstream`, specifically `--gene-analysis` on the subsetted data to find genes that are correlated with the trait within cell type A.

Thank you in advance :)

**Comment by martinjzhang** [comment]
Hi, this is statistically valid.
