### ISSUE TITLE
Using geneset from SMR result

### ISSUE THREAD

**Issue by Misaka-15134** [martinjzhang/scDRS#87]
Hi,

Thank you for providing such an interesting tool! In the discussion section of your article, you mention that the statistical correlation between individual cells (or cell types) and diseases does not imply causation. If I use a gene set that is not based on MAGMA, but rather results obtained from a transcriptome-SMR analysis, would it be feasible to input such a causal gene set?

In this case, can it be considered that the cell groups obtained from scDRS are the causal cell groups for the disease? I am very interested in this and hope to get your clarification!

**Comment by martinjzhang** [comment]
Hi, 

>In the discussion section of your article, you mention that the statistical correlation between individual cells (or cell types) and diseases does not imply causation. If I use a gene set that is not based on MAGMA, but rather results obtained from a transcriptome-SMR analysis, would it be feasible to input such a causal gene set?

Yes. scDRS is compatible with any gene sets. 

>In this case, can it be considered that the cell groups obtained from scDRS are the causal cell groups for the disease? I am very interested in this and hope to get your clarification!
I would be cautious about interpreting these findings as causal. Essentially, scDRS determines if the genes in the disease gene set are highly expressed in the cell population. This is fundamentally an association approach, and this nature won't change even if we modify the method for computing the disease gene set.
