### ISSUE TITLE
tcell.facs.annot.h5ad without GENE name

### ISSUE THREAD

**Issue by Davidseye** [martinjzhang/scDRS#91]
![scdrs](https://github.com/martinjzhang/scDRS/assets/92795943/570bc966-5493-4646-93ad-5c037f0fd1d2)
when i use the Tcell annot h5ad file, I notice that the name of gene is an ID, such as"0610007c21rik" ,not the name we usually use. This lead to no gene can be found in the .gs file and "skipped due to small size (n_gene=0)". I wonder how to solve it or annote it. BTW, I wonder  if I get a gene set not from magma, I can only get the order of genes, without z-score, can it be a legal .gs file?

**Comment by martinjzhang** [comment]
Those seem to be mouse genes. Did you try to specify the h5ad species to be mouse?

**Comment by Davidseye** [comment]
> Those seem to be mouse genes. Did you try to specify the h5ad species to be mouse?

thanks a lot , I made a mistake😢
