### ISSUE TITLE
use scdrs in a tissue seemlingly unrelated with the disease

### ISSUE THREAD

**Issue by Davidseye** [martinjzhang/scDRS#92]
when i use scdrs in a tissue seemlingly unrelated with the disease, such as , if i use scdrs to lung/kidney with the IBD statistics, and some cells are enriched  and the p-value is <0.05, does that make sense in a biological way?

**Comment by martinjzhang** [comment]
Hi, did you apply multiple testing correction? https://en.wikipedia.org/wiki/False_discovery_rate#History

**Comment by Davidseye** [comment]
FDR < 0.05? yeah, it passed

**Comment by martinjzhang** [comment]
there are immune cells in lung/kidney. if those are the associated cells, it is biologically plausible. If the cells are not immune cells, the discoveries may be spurious.

**Comment by Davidseye** [comment]
thanks, i got it. Appreciating for your prompt reply,thanks again!

**Comment by Davidseye** [comment]
> there are immune cells in lung/kidney. if those are the associated cells, it is biologically plausible. If the cells are not immune cells, the discoveries may be spurious.

HOW could I understand this relationship between the IBD and the immune cell outside the gut？those immune cells may have some tissue-specific features, but they still have the single cell PRS(enriched scdrs). or they are generally the same as those immune cells in the blood in gene expression.     BTW, I wonder if I can use scDRS to detect the smaller cell subset, such as all of them highly express some genes?

**Comment by Davidseye** [comment]
Thanks a lot! I understand.



---Original---
From: "Martin Jinye ***@***.***&gt;
Date: Thu, Sep 5, 2024 23:00 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [martinjzhang/scDRS] use scdrs in a tissue seemlingly unrelatedwith the disease (Issue #92)




  
HOW could I understand this relationship between the IBD and the immune cell outside the gut？those immune cells may have some tissue-specific features, but they still have the single cell PRS(enriched scdrs). or they are generally the same as those immune cells in the blood in gene expression. BTW, I wonder if I can use scDRS to detect the smaller cell subset, such as all of them highly express some genes?
  
At the current stage, I don't think scDRS can distinguish, e.g., immune cells from the gut vs. immune cells from the lung for IBD unless their gene expression profiles are considerably different. It is possible that both set of cells are significant, but immune cells from the gut have higher scDRS scores. Among all significant cells, the values of scDRS scores can distinguish subsets of more associated cells.
