### ISSUE TITLE
fail to get the "1000 top associated genes" based on MAGMA 

### ISSUE THREAD

**Issue by yihancc** [martinjzhang/scDRS#93]
Hi, thans for this wonderful tool!

I would like to generate .gs files for other diseases that are not in your article. Based on MAGMA, I used the association statistics from GWAS just as you suggested [https://github.com/martinjzhang/scDRS/issues/89](url) , but finally got only 59 genes for one disease instead of 1000 genes. 

I am worried that such a small number of genes will seriously affect my results. Could you please give me some advice on how to generate the "1000 most associated genes" based on MAGMA?

Thank you very much!

**Comment by martinjzhang** [comment]
59 genes should work. We have used genesets with 10-20 genes in the paper. 
For generating "1000 most associated genes", you will need genomewide association statistics. 
See instructions here: https://github.com/martinjzhang/scDRS/issues/2

**Comment by yihancc** [comment]
Thank you so much for your reply! I will have a try.
