### ISSUE TITLE
Questions about matched gene sets

### ISSUE THREAD

**Issue by HelloWorldLTY** [martinjzhang/scDRS#95]
Hi, thanks for your great work. I wonder if it is possible to share more details of selecting matched control genes. e.g., how the threshold of matched mean/variance/other factors affects downstream analysis. Are they hyper-parameters that we can tune? Thanks.

**Comment by martinjzhang** [comment]
We match by 400 (20*20) mean-variance bins. 
- Here is where the mean-variance bins are computed: https://github.com/martinjzhang/scDRS/blob/c4dfcc09b8bfda7c26e5bb8674560c5bf9048bab/bin/scdrs#L248-L250
- Details of `scdrs.preprocess` here https://martinjzhang.github.io/scDRS/reference/scdrs.preprocess.html 
- It will generate a column of `mean_var` in `adata.uns[“SCDRS_PARAM”]["GENE_STATS"]`, and will be later used in `scdrs.score_cell`: https://github.com/martinjzhang/scDRS/blob/c4dfcc09b8bfda7c26e5bb8674560c5bf9048bab/bin/scdrs#L264-L274

**Comment by HelloWorldLTY** [comment]
Got it, thanks a lot!
